apiVersion: v1
items:
- apiVersion: alb.networking.azure.io/v1
  kind: HealthCheckPolicy
  metadata:
    annotations:
    name: calculator-multicalculator-gw-health-calculator
    namespace: calculator
  spec:
    default:
      healthyThreshold: 1
      http:
        match:
          statusCodes:
          - end: 299
            start: 200
        path: /healthz
      interval: 5s
      port: 8080
      protocol: HTTP
      timeout: 3s
      unhealthyThreshold: 3
    targetRef:
      group: ""
      kind: Service
      name: calculator-multicalculator-frontend-svc
      namespace: calculator
kind: List