apiVersion: "v1"
kind: Pod
metadata:
  name: helloworld
  labels:
    release: V76
    app: helloworld-demo
spec:
  containers:
    - name: aci-helloworld
      image: dz1workshopacr.azurecr.io/phoenix:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "200m"
        limits:
          memory: "256Mi"
          cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  labels:
    name: helloworld-svc
    app: helloworld-svc  
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: helloworld-demo
