apiVersion: v1
kind: Service
metadata:
  name: calcfrontendsvc
  labels:
    name: calcfrontendsvc
    app: calculator
spec:
  selector:
    name: calcfrontend 
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP