apiVersion: "v1"
kind: Pod
metadata:
  name: calcfrontend
  labels:
    name: calcfrontend
    app: calculator
spec:
  containers:
    - name: calcfrontend
      image: dzregistry.azurecr.io/calc/calc-frontend:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      env:       
        - name: "ENDPOINT"
          value: "calcbackendsvc"
        - name: "INSTRUMENTATIONKEY"
          valueFrom:
            secretKeyRef:
              name: appinsightsecret
              key: appinsightskey
        - name: "PORT"
          value: "80"              