apiVersion: v1
kind: Service
metadata:
  name: calcfrontendsvc
  labels:
    name: calcfrontendsvc
    app: calculator
spec:
  selector:
    name: jscalcfrontend 
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jscalcfrontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: jscalcfrontend
      app: calculator
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: jscalcfrontend
        app: calculator
    spec:
      containers:
      - name: jscalcfrontend
        image: denniszielke/js-calc-frontend:latest
        imagePullPolicy: Always 
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "ENDPOINT"
            value: "calcbackendsvc"
          - name: "PORT"
            value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: calcbackendsvc
  labels:
    name: calcbackendsvc
    app: calculator 
spec:
  ports:
  - port: 80
    name: calcbackend
    targetPort: 80
  selector:
    role: calcbackend
    app: calculator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jscalcbackend
spec:
  replicas: 3
  selector:
    matchLabels:
        name: jscalcbackend
        role: calcbackend
        app: calculator
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: jscalcbackend
        role: calcbackend
        app: calculator
    spec:
      containers:
      - name: calcbackend
        image: denniszielke/js-calc-backend:latest
        imagePullPolicy: Always 
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocalcbackend
spec:
  replicas: 3
  selector:
    matchLabels:
        name: jscalcbackend
        role: calcbackend
        app: calculator
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: gocalcbackend
        role: calcbackend
        app: calculator
    spec:
      containers:
      - name: gocalcbackend
        image: denniszielke/go-calc-backend:latest
        imagePullPolicy: Always 
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "80"
