{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "multicalculator.fullname" . }}
  labels:
    {{- include "multicalculator.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  rules:
{{- if .Values.canary }}
  - matches:
    - headers:
      - type: Exact
        name: slot
        value: canary
    backendRefs:
    - name: {{ include "multicalculator.fullname" . }}-backend-svc
      port: {{ .Values.service.port }}
{{- else }}
  - backendRefs:
    - name: {{ include "multicalculator.fullname" . }}-frontend-svc
      port: {{ .Values.service.port }}
{{- end }}
{{- end }}
